### ISSUE TITLE
Generate id based on attribute, not anchor text

### ISSUE THREAD

**Issue by juanjosezg** [mrwweb/clicky-menus#11]
It is necessary to change the way in which the ids of the submenus are generated .. it is better to be based on the id of the parent or the container div ... currently it is based on the text of the link that has the submenu but it causes problems when you have the same menu in two different parts of the website.

![aria](https://user-images.githubusercontent.com/58767/138725859-721b945e-6ce1-4653-b5c5-e3bf5c49b898.png)

**Comment by mrwweb** [comment]
@juanjosezg I just pushed an update that adds an iterator for each menu instance that resolves this issue. If you ever test it, I'd love to know if it works for you!
