### ISSUE TITLE
Feature request: NPM Package

### ISSUE THREAD

**Issue by ajplopez** [mrwweb/clicky-menus#16]
It would be fantastic if this was something we could install using NPM.

I would use it all the time.

**Comment by mrwweb** [comment]
@ajplopez I just published [clicky-menus on NPM](https://www.npmjs.com/package/clicky-menus)!

I have never published a package before, so let me know if there are any changes that would make it easier to use.

**Comment by ajplopez** [comment]
Excellent! Good timing because I needed this. Works good so far.
