### ISSUE TITLE
Question: Can clicky menus be applied to only the 2nd level?

### ISSUE THREAD

**Issue by ajplopez** [mrwweb/clicky-menus#23]
I'm working on a site where there's a possibility they will want it so that when the user hovers over the 1st level, it dropdowns a menu that shows the 2nd level.

Then when they click on the 2nd level item, assuming it has children, it will click to open the 3rd level menu.

Is that possible using this script? Would it just be a matter of setting up multiple click menus?

**Comment by mrwweb** [comment]
Currently that is not possible, and I actually have hoped to improve the CSS to make that more obvious by not hiding 2nd-level <ul>s. I tend to see tertiary / fly-out menus as a "navigation smell" and think that [mega menus are almost always the better solution](https://www.nngroup.com/articles/mega-menus-work-well/). [Stuff like this.](https://devcollaborative.com/blog/entertainment-community-funds-redesigned-website-navigation-connecting-more-actors-services)

So for the foreseeable future, I don't plan to add this feature. I recognize that people might find it useful, but it's just not the need I'm hoping to meet with this script.
