### ISSUE TITLE
Would you consider dual-licensing your code under MIT/BSD?

### ISSUE THREAD

**Issue by utrenkner** [mrwweb/clicky-menus#4]
Thank you for this nice click-menu. Your reasoning on CSS-Tricks resonates with me and I would like to use this in one of my projects.

While I am not anti-GPL, I would like to ask whether you could consider to license it (also) under a permissive license such as MIT or BSD? I absolutely don't mind anyone to copy and adapt _our_ HTML/CSS/JS. But GPL forces us to always check that we we do not combine it with code under a conflicting license.

**Comment by utrenkner** [comment]
Any thoughts on this?

I would really love to use your code to replace a current mobile navigation, which suffers from a bad Cumulative Layout Shift (CLS). If you keep clicky-menues GPL-only, I would have to review any front-end code for incompatible licenses. I would be super happy, if you could spare us from this legal work and make the code available (also) under MIT/BSD or similar license.

**Comment by mrwweb** [comment]
@utrenkner I'll admit that my full understanding of the implications is limited, but I'm happy for it to get used far and wide. Let's do it. Can you submit a PR?

**Comment by utrenkner** [comment]
Thank you!!! I just submitted such a PR.

**Comment by mrwweb** [comment]
Closed by #5
