### ISSUE TITLE
Consider support for multiple levels of submenu

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/clicky-menus#8]
While I don't like it, it would make the script more useful to more people if this supported multiple levels of submenus. That said, doing then _must not_ come at the expense of being able to make "mega menus" that show nested lists within the top-level submenu. Therefore, the secondary submenu feature would need to be configurable in a way that makes it opt-in.

**Comment by timburg1** [comment]
I'd really appreciate support for multi-level menus. The accessibility of this offering is great - I'm a blind developer supporting blind end-users, so this is vital for me. However, I have multiple projects that need to create multi-level menus dynamically by reading in an XML file that defines the interface and this is where Clicky falls short.

**Comment by ajplopez** [comment]
I third this (no pun intended). This would be a fantastic addition and I would use this script even more.

**Comment by ajplopez** [comment]
I'm working on a website right now that could use this. It's a mega menu where clicking on the top level links toggle open the submenu but inside the submenu are 2nd and 3rd level links.

In my design, in this case, I just want the top level to open links. The second level parents should just display the 3rd level link below it and nothing else. But they themselves are links so they should also _not_ turn into buttons.

**Comment by mrwweb** [comment]
@ajplopez I'd love to make it easier to handle that, although there is one thing you can do to make that easier. Take a look at the ["Custom Submenu Selector"](https://github.com/mrwweb/clicky-menus?tab=readme-ov-file#custom-submenu-selector):

```html
<ul class="clicky-menu" data-clicky-submenu-selector=".clicky-menu > li > ul">
    <!-- menu items -->
</ul>```

Doing that will only target the first level of nested menus as hidable submenus. You'll still need to do a bit of work to reset some of the sites (`visibility: visible` for sure), but that at least gets you past the script trying to show/hide nested/tertiary submenus.

**Comment by ajplopez** [comment]
@mrwweb Yes! Sorry, I realized after what I needed so I deleted that last comment. Got it working great.

**Comment by ajplopez** [comment]
I'm working on a new project where this would be super useful.

**Comment by mrwweb** [comment]
I've thought about this for a long time and am closing this issue with no plans to add the feature. For folks seeking this, I _strongly_ recommend considering [a mega menu](https://www.nngroup.com/articles/mega-menus-work-well/) as an alternative.
