### ISSUE TITLE
Include animations in demo

### ISSUE THREAD

**Issue by 7Narwen** [mrwweb/clicky-menus#9]
I feels stupid myself.  You've noted that "using visibility instead of display allows for easier transitions and animation of submenus". 
So I've playing with [your demo](https://codepen.io/mrwweb/pen/pXqKZO) and trying to add animation/transition to icon and submenu, but I couldn't make it work. Could you please add some animation as example?

**Comment by mrwweb** [comment]
That's not a bad idea, but it might take a while.

For now, check out https://earthgenwa.org which is using this script and includes both animated submenu indicators and submenus.

And don't forget to respect `@media( prefers-reduced-motion )`!

**Comment by 7Narwen** [comment]
Thank you for link!
